format = """
[░▒▓](#ABAFBF)\
[  ](bg:#ABAFBF fg:#212337)\
[](bg:#99C1F1 fg:#ABAFBF)\
$directory\
[](fg:#99C1F1 bg:#6D8DAD)\
$git_branch\
$git_status\
[](fg:#6D8DAD bg:#2b2e4c)\
$nodejs\
$rust\
$golang\
$php\
[](fg:#2B2E4C bg:#212337)\
$time\
[ ](fg:#212337)\
\n$character"""

[directory]
style = "fg:#212337 bg:#99C1F1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#6D8DAD"
format = '[[ $symbol $branch ](fg:#212337 bg:#6D8DAD)]($style)'

[git_status]
style = "bg:#6D8DAD"
format = '[[($all_status$ahead_behind )](fg:#212337 bg:#6D8DAD)]($style)'

[nodejs]
symbol = ""
style = "bg:#6D8DAD"
format = '[[ $symbol ($version) ](fg:#212337 bg:#6D8DAD)]($style)'

[rust]
symbol = ""
style = "bg:#6D8DAD"
format = '[[ $symbol ($version) ](fg:#212337 bg:#6D8DAD)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#6D8DAD"
format = '[[ $symbol ($version) ](fg:#212337 bg:#6D8DAD)]($style)'

[php]
symbol = ""
style = "bg:#6D8DAD"
format = '[[ $symbol ($version) ](fg:#212337 bg:#6D8DAD)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6D8DAD"
format = '[[  $time ](fg:#ABAFBF bg:#212337)]($style)'
